config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # resources :raw_materials
  resources :inventories, only: [:edit, :update]
  resources :record_logs, only: [:index]
  resources :raw_materials
  # root to: "raw_materials#index"
  patch 'add', to: 'pages#add_quantity', as: :add_quantity
  patch 'subtract', to: 'pages#subtract_quantity', as: :subtract_quantity
  patch 'sell_product', to: 'pages#sell_product', as: :sell_product
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/final_product.rb
class FinalProduct < ApplicationRecord
  has_many :products
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :raw_material
  validates :quantity, numericality: { greater_than: -1 }

  # def update_quantity(quantity)
  #   self.quantity += quantity
  # end

  def sell_inventory(material, quantity)
    material.quantity -= quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :final_product
  belongs_to :raw_material
end

app/models/raw_material.rb
class RawMaterial < ApplicationRecord
  has_many :inventories
  has_many :products
end

app/models/record_log.rb
class RecordLog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # def authorize_admin
  #   redirect_to :back, status: 401 unless current_user.admin
  #   #redirects to previous page
  # end

  # private
  # def authenticate_user!
  #   if user_signed_in?
  #     super
  #   else
  #     redirect_to new_user_session_path, :notice => 'if you want to add a notice'
  #     ## if you want render 404 page
  #     ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
  #   end
  # end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :find_inventory, only: [:edit, :update]

  def edit
  end

  def update
    if @inventory.update!(inventory_params)
      previous_quantity = @inventory.quantity_before_last_save
      RecordLog.create!(title: "Alteração da quantidade de #{@inventory.raw_material.name} - #{previous_quantity} para #{@inventory.quantity} unidades", date: Time.now.strftime("%d/%m/%Y %H:%M"))
      redirect_to root_path 
    end
  end

  private

  def find_inventory
    @inventory = Inventory.find(params[:id])
  end

  def inventory_params
    params.require(:inventory).permit(:quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_material, only: [:add_quantity, :subtract_quantity]

  def home
    @inventories = Inventory.all.sort_by { |material| material.raw_material.name }
    @inventory = Inventory.new
  end

  def sell_product
    quantity_multiplier = params[:quantity].to_i
    final_product = FinalProduct.find_by_name(params[:product_to_sell])
    materials_array = final_product.products  
    product_bm_hash = get_final_product_bm_hash(materials_array, quantity_multiplier)
    inventory_quantity_hash = get_inventory_quantity_hash(materials_array)
    record_log = RecordLog.new(title: "Venda de #{quantity_multiplier} quantidade(s) de #{final_product.name}", date: Time.now.strftime("%d/%m/%Y %H:%M"))

    materials_array.each do |product|
      product.raw_material.inventories.each do |inventory_material|
        record_final_product_sale(inventory_material, product_bm_hash, inventory_quantity_hash, final_product, record_log)
      end
    end
    redirect_to root_path
  end

  private

  def find_material
    @inventory_material = Inventory.find(params[:material])
  end

  def get_final_product_bm_hash(final_product_array, quantity_multiplier)
    product_bm_hash = {}
    final_product_array.each do |material|
      product_bm_hash[material.raw_material.name] = material.quantity * quantity_multiplier
    end

    return product_bm_hash
  end

  def get_inventory_quantity_hash(final_product_array)
    inventory_hash = {}
    final_product_array.each do |material|
      inventories_material = material.raw_material.inventories
      inventories_material.each do |inventory_material|
        inventory_hash[inventory_material.raw_material.name] = inventory_material.quantity
      end
    end

    return inventory_hash
  end

  def validate_quantity(bm_hash, inventory_hash)
    results_array = []
    results_array_inv = []
    results_array_bm = []
    bm_hash.each { |key, value| 
      results_array << (inventory_hash[key] >= value)
      results_array_inv << inventory_hash[key]
      results_array_bm << value
    }
    return results_array.include? false
  end

  def record_final_product_sale(inventory_material, product_bm_hash, inventory_quantity_hash, product_name, record_log)
    if validate_quantity(product_bm_hash, inventory_quantity_hash) == false
      inventory_material.sell_inventory(inventory_material, product_bm_hash[inventory_material.raw_material.name])
      inventory_material.save
      record_log.save
    else
      flash[:alert] = "Você não pode baixar o material #{product_name.name} pois não há estoque suficiente"
    end
  end
end

app/controllers/record_logs_controller.rb
class RecordLogsController < ApplicationController
  def index
    display = params[:query]
    display_all = params[:display]
    if RecordLog.all.empty?
      @record_logs = []
      @record_text = "(Não há nenhum registro)"
    elsif (display == "todos") || (display_all == "display_all")
      @record_logs = RecordLog.all.order("date DESC")
      @record_text = "(Todos os registros)"
    elsif display != nil
      @record_logs = RecordLog.all.order("date DESC")[0..(display.to_i - 1)]
      @record_text = "(Últimos #{display.to_i} registros)"
    else
      @record_logs = RecordLog.all.order("date DESC")[0..29]
      @record_text = "(Últimos 30 registros)"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inventories/edit.html.erb
<div class="header-estoque">Produto: <%= @inventory.raw_material.name %></div>
<div class="container edit-container">
  <div class="p-4">
    <%= simple_form_for(@inventory) do |f| %>
      <%= f.error_notification %>
      <%= f.input :quantity, required: false, label: 'Quantidade' %>
      <div class="form-actions">
        <%= link_to "Retornar à página principal", root_path, class: "btn btn-secondary" %>
        <%= f.button :submit, 'Mudar quantidade', class: "btn btn-enerpel", data: { confirm: "Tem certeza que deseja alterar a quantidade do material: #{@inventory.raw_material.name}?" } %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Enerpel - Controle de Estoque</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_log_as_admin.html.erb
<div class="header-estoque">Você precisa ser administrador para acessar</div>
<div class="not-logged-in-body">
  <%= link_to "Logar como administrador", destroy_user_session_path, method: :delete, class:"btn btn-enerpel" %>
</div>

app/views/pages/_modal_create.html.erb
<div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-size" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Lista de Itens a Venda</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="sell-links">
          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Caixa OPGW - Torre"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Caixa OPGW - Torre", class: "btn btn-enerpel w-75" %>
          <% end %>

          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Caixa OPGW - Pórtico"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Caixa OPGW - Pórtico", class: "btn btn-enerpel w-75" %>
          <% end %>

          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Cruzeta com Suporte - Torre"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Cruzeta com Suporte - Torre", class: "btn btn-enerpel w-75" %>
          <% end %>

          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Cruzeta com Suporte - Pórtico"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Cruzeta com Suporte - Pórtico", class: "btn btn-enerpel w-75" %>
          <% end %>

          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Grampo Guia de Descida em Torre - (9:00 a 11:99)"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Grampo Guia de Descida em Torre - (9:00 a 11:99)", class: "btn btn-enerpel w-75" %>
          <% end %>

          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Grampo Guia de Descida em Torre - (12:00 a 13:99)"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Grampo Guia de Descida em Torre - (12:00 a 13:99)", class: "btn btn-enerpel w-75" %>
          <% end %>

          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Grampo Guia de Descida em Torre - (14:00 a 15:99)"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Grampo Guia de Descida em Torre - (14:00 a 15:99)", class: "btn btn-enerpel w-75" %>
          <% end %>

          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Grampo Guia de Descida em Torre - (16:00 a 17:99)"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Grampo Guia de Descida em Torre - (16:00 a 17:99)", class: "btn btn-enerpel w-75" %>
          <% end %>

          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Grampo Guia de Descida em Pórtico - (9:00 a 11:99)"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Grampo Guia de Descida em Pórtico - (9:00 a 11:99)", class: "btn btn-enerpel w-75" %>
          <% end %>

          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Grampo Guia de Descida em Pórtico - (12:00 a 13:99)"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Grampo Guia de Descida em Pórtico - (12:00 a 13:99)", class: "btn btn-enerpel w-75" %>
          <% end %>
          
          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Grampo Guia de Descida em Pórtico - (14:00 a 15:99)"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Grampo Guia de Descida em Pórtico - (14:00 a 15:99)", class: "btn btn-enerpel w-75" %>
          <% end %>
          
          <%= form_for @inventory, url: sell_product_path(product_to_sell: "Grampo Guia de Descida em Pórtico - (16:00 a 17:99)"), method: :patch, html: { class: "d-flex align-items-center mb-1 modal-form" } do |f| %>
            <%= number_field_tag :quantity, nil, class: "w-25 modal-input", placeholder:"Digite a quantidade" %>
            <%= f.submit "Registrar venda Grampo Guia de Descida em Pórtico - (16:00 a 17:99)", class: "btn btn-enerpel w-75" %>
          <% end %>

        </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'modal' %>

app/views/pages/home.html.erb
<% if current_user.admin? %>
<div class="header-estoque">Controle de Estoque</div>
  <div class="container">
      

    <button type="button" class="btn btn-enerpel ml-4 mt-4 mb-4" data-toggle="modal" data-target="#modalExemplo">
      Registrar Venda de Produto
    </button>
    <%= render 'modal_create' %>

    <table class="index-table">
      <thead>
        <tr class="table-header pl-4">
          <th class="pr-5 pl-4">Material</th>
          <th class="text-right">Quantidade</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @inventories.each do |material| %>
          <tr>
            <td class="pl-4"><%= material.raw_material.name %></td>
            <td class="text-right"><%= material.quantity %></td>
            
            <td class="text-center"><%= link_to "Editar quantidade", edit_inventory_path(material.id), previous_quantity: material,  class:"btn btn-enerpel w-75" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <%= render 'log_as_admin' %>
<% end %>
<%= render 'shared/footer' %>

app/views/record_logs/index.html.erb
<% if current_user.admin? %>
  <div class="header-estoque">Controle de Registros <%= @record_text %></div>
  <div class="container mb-5">
    <p id="notice"><%= notice %></p>
    <%= link_to 'Retornar ao Controle de Estoque', root_path, class:"btn btn-secondary ml-4 mt-4 mb-4" %>
    <%= link_to 'Mostrar todos os registros', record_logs_path(:display => "display_all"), class:"btn btn-enerpel ml-4 mt-4 mb-4" %>
  
  <form class="form-inline ml-4 mb-4">
      <input class="form-control form-width" name="query" type="search" placeholder="Digite a quantidade de registros a ser mostrada" aria-label="Search" value="">
      <button class="btn btn-enerpel" type="submit">Search</button>
    </form>
    
    <table class="index-table">
      <thead>
        <tr class="table-header pl-4">
          <th class="pl-4">Data e hora</th>
          <th class="text-left">Descrição do registro</th>
        </tr>
      </thead>
      <tbody>
        <% count = 1 %>
      <% @record_logs.each do |record| %>
        <tr>
          <td class="pl-4"><%= "#{count} - " %><%= record.date %></td>
          <td><%= record.title %></td>
        </tr>
        <% count += 1 %>

      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <%= render 'pages/log_as_admin' %>
<% end %>
<%= render 'shared/footer' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/vishizaki" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://br.linkedin.com/in/vinicius-ishizaki-0a258b31" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    ENERPEL Teleinformática
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Registro de Movimentação', record_logs_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>